export const ErrorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    INVALID_INPUT: 'INVALID_INPUT',
    DATABASE_ERROR: 'DATABASE_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED'
} as const;
  
export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];